version: '3'

services:
  
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node

  node:
    build: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s docker-entrypoint.sh
    command: node index.js
    networks: 
      - node-network
    #volumes:
    #- ./node:/usr/src/app
    tty: true
    depends_on:
      - db
   
  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  

networks:
  node-network:
    driver: bridge